### ISSUE TITLE
Generate dhparam faster + more entropy

### ISSUE THREAD

**Issue by JOduMonT** [SS88UK/VestaCP-Server-Installer#3]
In this part : Let's fix NGINX up! This will take a very long time.

you should install haveged

```
yum install -y haveged
systemctl enable haveged
systemctl start haveged
```

than generate the dhparam
it will be faster ;)

**Comment by plutocrat** [comment]
Alternatively, consider adding the -dsaparam option. It has helped me on other server setups. eg. 

openssl dhparam -dsaparam -out /etc/ssl/private/dhparam.pem 4096

"This option instructs OpenSSL to produce "DSA-like" DH parameters (p is such that p-1 is a multiple of a smaller prime q, and the generator has multiplicative order q). This is considerably faster because it does not need to nest the primality tests, and thus only thousands, not millions, of candidates will be generated and tested."

**Comment by Neoboffin** [comment]
Thank you @plutocrat - I've added this to the installer.
